{% set name = "legacy-suitcase" %}
{% set version = "0.7.0" %}
{% set sha256 = "04ec6485bd885312155e440d1f35097f3c664abd65ee52ca57fff1d93f1ef79d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/bluesky/suitcase-core/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - databroker
    - h5py
    - numpy

test:
  requires:
    - python {{ python_min }}
  imports:
    - suitcase
    - suitcase.hdf5

about:
  home: https://github.com/bluesky/suitcase-core
  license:  BSD-3-Clause
  license_file: LICENSE
  summary: Legacy HDF5 exporter used at NSLS-II ESM-1 and ESM-2
  dev_url: https://github.com/bluesky/suitcase-core
  doc_url: https://blueskyproject.io/suitcase

extra:
  recipe-maintainers:
    - mrakitin
    - kbeeperez
    - conda-forge/event-model
